tweepy

Official documentation: https://docs.tweepy.org/en/stable/

Ref: https://dev.to/twitterdev/a-comprehensive-guide-for-using-the-twitter-api-v2-using-tweepy-in-python-15d9

In [8]:
import tweepy
import datetime
import pandas as pd
import json
import requests

In [9]:
# Update this variable with YOUR OWN Twitter Bearer Token
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAOlFYQEAAAAA564Nq2buxWcuVMiwrxqNcrlFwfI%3DO6AkqhR3vBDKQnVJWaL04FQp0yaMBbz7GCeCLWwdUhba1NU6le'

client = tweepy.Client(bearer_token=BEARER_TOKEN, return_type=requests.Response)

In [12]:
'''
Searching for Tweets from the last 7 days

We can use the search_recent_tweets function available in Tweepy.
You will have to pass it a search query to specify the data that you are looking for.

Below, we will search for for Tweets from the last days from the 
Twitter handle realDonaldTrump and we are excluding retweets using -is:retweet.

By default, a request returns 10 Tweets.
If you want more than 10 Tweets per request, you can specify that using the max_results parameter.
The maximum Tweets per request is 100.
'''
# Replace with your own search query
handle = 'KimKardashian'
query = 'from:' + handle + ' -is:retweet'

tweets1 = client.search_recent_tweets(
            query=query,
            tweet_fields=['context_annotations', 'created_at'],
            max_results=100)

In [13]:
'''
Convert to pandas Dataframe
'''

# Save data as dictionary
tweets_dict1 = tweets1.json()

# Extract "data" value from dictionary
tweets_data1 = tweets_dict1['data'] 

# Transform to pandas Dataframe
df1 = pd.json_normalize(tweets_data1)

df1

,context_annotations,text,created_at,id
0,"[{'domain': {'id': '10', 'name': 'Person', 'de...",You can expect a wide range of scent notes fro...,2022-01-19T20:02:02.000Z,1483892525014282243
1,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Coming Soon: Jeff Leatham II by @KKWFragrance....,2022-01-19T20:00:58.000Z,1483892260605349888
2,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Beach üÖøÔ∏èarty https://t.co/0rlc0wo7iE,2022-01-19T13:47:50.000Z,1483798357633945602
3,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Mother Nature üßúüèª‚Äç‚ôÄÔ∏è https://t.co/kufiSWM2Dm,2022-01-17T19:45:04.000Z,1483163481947922442
4,"[{'domain': {'id': '10', 'name': 'Person', 'de...",üéÇ ‚ô•Ô∏è https://t.co/B5KQ0AvOkF,2022-01-15T16:08:17.000Z,1482384151584014336
5,"[{'domain': {'id': '10', 'name': 'Person', 'de...",üíï https://t.co/QzJpnLCajW,2022-01-15T16:05:50.000Z,1482383535486816256
6,"[{'domain': {'id': '10', 'name': 'Person', 'de...",I can‚Äôt wait to celebrate with all of the Barb...,2022-01-15T15:37:05.000Z,1482376298118877184
7,"[{'domain': {'id': '10', 'name': 'Person', 'de...",My birthday baby girl Chi Chi turns 4 today! M...,2022-01-15T15:36:32.000Z,1482376160117886980
8,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Just added new items on my #KardashianKloset üõç...,2022-01-14T18:01:45.000Z,1482050315503357960
9,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Just dropped @SKIMS Faux Leather! Available no...,2022-01-14T17:00:08.000Z,1482034810952450049
10,"[{'domain': {'id': '10', 'name': 'Person', 'de...",What are some good shows to watch? Could be ne...,2022-01-14T07:29:21.000Z,1481891168069701634
11,"[{'domain': {'id': '10', 'name': 'Person', 'de...",I was lol but finally catching up on all the g...,2022-01-14T07:28:43.000Z,1481891010762264577
12,"[{'domain': {'id': '3', 'name': 'TV Shows', 'd...",@sarahrhoward Not sure lol I‚Äôm up organizing a...,2022-01-14T07:27:33.000Z,1481890717760823297
13,"[{'domain': {'id': '3', 'name': 'TV Shows', 'd...",Oh and also Just Like That the new chapter of ...,2022-01-14T07:25:51.000Z,1481890287966310402
14,"[{'domain': {'id': '3', 'name': 'TV Shows', 'd...",Just started some old school shows I‚Äôve never ...,2022-01-14T07:15:22.000Z,1481887649501569025
15,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Love u Jake! I‚Äôm DMing u RN https://t.co/BhDSG...,2022-01-14T05:11:45.000Z,1481856539447025665
16,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Thank you to the incredible Team USA athletes ...,2022-01-13T17:18:43.000Z,1481677098573910016
17,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Introducing @SKIMS for @TeamUSA: a special col...,2022-01-13T17:04:30.000Z,1481673522275487747

In [14]:
'''
If you want to get Tweets for a specific time-period, you can specify the time-period
using the start_time and end_time parameters, as shown in the example below:
'''

# Replace with time period of your choice
start_time = '2022-01-15T00:00:00Z'

# Replace with time period of your choice
end_time = '2022-01-16T00:00:00Z'


# Replace with your own search query
handle = 'KimKardashian'
query = 'from:' + handle + ' -is:retweet'

tweets2 = client.search_recent_tweets(
            query=query,
            tweet_fields=['context_annotations', 'created_at'],
            start_time=start_time,
            end_time=end_time,
            max_results=100)

'''
Convert to pandas Dataframe
'''

tweets2.json()

{'data': [{'created_at': '2022-01-15T16:08:17.000Z',
   'id': '1482384151584014336',
   'context_annotations': [{'domain': {'id': '10',
      'name': 'Person',
      'description': 'Named people in the world like Nelson Mandela'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}},
    {'domain': {'id': '58',
      'name': 'Entertainment Personality',
      'description': 'An entertainment personality in the world, like Anderson Cooper or Miranda Sings'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}}],
   'text': 'üéÇ ‚ô•Ô∏è https://t.co/B5KQ0AvOkF'},
  {'created_at': '2022-01-15T16:05:50.000Z',
   'id': '1482383535486816256',
   'context_annotations': [{'domain': {'id': '10',
      'name': 'Person',
      'description': 'Named people in the world like Nelson Mandela'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}},
    {'domain': {'id': '58',
      'name': 'Entertainment Personality',
      'description': 'An entertainment personality in the world, like Anderson Cooper or Miranda Sings'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}}],
   'text': 'üíï https://t.co/QzJpnLCajW'},
  {'created_at': '2022-01-15T15:37:05.000Z',
   'id': '1482376298118877184',
   'context_annotations': [{'domain': {'id': '10',
      'name': 'Person',
      'description': 'Named people in the world like Nelson Mandela'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}},
    {'domain': {'id': '58',
      'name': 'Entertainment Personality',
      'description': 'An entertainment personality in the world, like Anderson Cooper or Miranda Sings'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}}],
   'text': 'I can‚Äôt wait to celebrate with all of the Barbies and LOL Dolls a girl could dream of lol. You really have brought so much joy into our family and I love you so so soooo much!!!! https://t.co/Oz9jSZAkwq'},
  {'created_at': '2022-01-15T15:36:32.000Z',
   'id': '1482376160117886980',
   'context_annotations': [{'domain': {'id': '10',
      'name': 'Person',
      'description': 'Named people in the world like Nelson Mandela'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}},
    {'domain': {'id': '58',
      'name': 'Entertainment Personality',
      'description': 'An entertainment personality in the world, like Anderson Cooper or Miranda Sings'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}}],
   'text': 'My birthday baby girl Chi Chi turns 4 today! My independent baby girl twin. You are the most lovable huggable snuggable baby girl on the planet. The ultimate princess! https://t.co/DEycELflpH'}],
 'meta': {'newest_id': '1482384151584014336',
  'oldest_id': '1482376160117886980',
  'result_count': 4}}

In [15]:
'''
Writing Tweets to a text file

This example shows how you can write the Tweet IDs for each Tweet obtained 
for a search result, to a text file.

Make sure to replace the file_name with the a name of your chosing.

If you wish to write other fields to the text file, make sure to adjust the script below accordingly.
'''

file_name = 'tweets.txt'

df1.to_csv(file_name, index=False, encoding='utf-8')

# If you want a different delimiter, say, tab or '\t'
# You can do:
#    df2.to_csv(file_name, index=False, encoding='utf-8', sep='\t')