tweepy

Official documentation: https://docs.tweepy.org/en/stable/

Ref: https://dev.to/twitterdev/a-comprehensive-guide-for-using-the-twitter-api-v2-using-tweepy-in-python-15d9

In [1]:
import tweepy
import datetime
import pandas as pd
import json
import requests

In [2]:
# Update this variable with YOUR OWN Twitter Bearer Token
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAOlFYQEAAAAA564Nq2buxWcuVMiwrxqNcrlFwfI%3DO6AkqhR3vBDKQnVJWaL04FQp0yaMBbz7GCeCLWwdUhba1NU6le'

client = tweepy.Client(bearer_token=BEARER_TOKEN, return_type=requests.Response)

In [3]:
'''
Searching for Tweets from the last 7 days

We can use the search_recent_tweets function available in Tweepy.
You will have to pass it a search query to specify the data that you are looking for.

Below, we will search for for Tweets from the last days from the 
Twitter handle realDonaldTrump and we are excluding retweets using -is:retweet.

By default, a request returns 10 Tweets.
If you want more than 10 Tweets per request, you can specify that using the max_results parameter.
The maximum Tweets per request is 100.
'''
# Replace with your own search query
handle = 'KimKardashian'
query = 'from:' + handle + ' -is:retweet'

tweets1 = client.search_recent_tweets(
            query=query,
            tweet_fields=['context_annotations', 'created_at'],
            max_results=100)

In [4]:
'''
Convert to pandas Dataframe
'''

# Save data as dictionary
tweets_dict1 = tweets1.json()

# Extract "data" value from dictionary
tweets_data1 = tweets_dict1['data'] 

# Transform to pandas Dataframe
df1 = pd.json_normalize(tweets_data1)

df1

,created_at,text,context_annotations,id
0,2022-01-26T02:55:09.000Z,Which are you guys excited for tomorrow??? I l...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1486170817310298115
1,2022-01-25T23:52:13.000Z,long time no sea üåä üêö https://t.co/LtJrwUQ8x7,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1486124781430718465
2,2022-01-25T17:01:34.000Z,Just drop NEW @skims for @TeamUSA! Shop now fo...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1486021437446000641
3,2022-01-24T19:39:45.000Z,"My condolences go to Manfred‚Äôs family, friends...","[{'domain': {'id': '10', 'name': 'Person', 'de...",1485698860496285700
4,2022-01-24T19:39:41.000Z,You always said beauty will save the world - a...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1485698841265336323
5,2022-01-24T19:39:34.000Z,There was so much more for you to show the wor...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1485698812630863873
6,2022-01-24T19:39:29.000Z,Manfred Thierry Mugler üíî My heart breaks. Ther...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1485698790677835776
7,2022-01-21T18:29:10.000Z,Just added new items to my #KardashianKloset h...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1484593931157336065
8,2022-01-21T16:50:04.000Z,Always ‚úåüèºüíó https://t.co/w3KBqX7RbW,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1484568994463895552
9,2022-01-20T22:11:34.000Z,Just dropped NEW @skims Outdoor! Shop now at h...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1484287511341899776
10,2022-01-19T20:02:02.000Z,You can expect a wide range of scent notes fro...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1483892525014282243
11,2022-01-19T20:00:58.000Z,Coming Soon: Jeff Leatham II by @KKWFragrance....,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1483892260605349888
12,2022-01-19T13:47:50.000Z,Beach üÖøÔ∏èarty https://t.co/0rlc0wo7iE,"[{'domain': {'id': '10', 'name': 'Person', 'de...",1483798357633945602

In [7]:
'''
If you want to get Tweets for a specific time-period, you can specify the time-period
using the start_time and end_time parameters, as shown in the example below:
'''

# Replace with time period of your choice
# start_time = '2022-01-15T00:00:00Z'

# # Replace with time period of your choice
# end_time = '2022-01-16T00:00:00Z'

# Replace with time period of your choice
start_time = '2022-01-20T00:00:00Z'

# # Replace with time period of your choice
end_time = '2022-01-21T00:00:00Z'


# Replace with your own search query
handle = 'KimKardashian'
query = 'from:' + handle + ' -is:retweet'

tweets2 = client.search_recent_tweets(
            query=query,
            tweet_fields=['context_annotations', 'created_at'],
            start_time=start_time,
            end_time=end_time,
            max_results=100)

'''
Convert to pandas Dataframe
'''

tweets2.json()

{'data': [{'id': '1484287511341899776',
   'created_at': '2022-01-20T22:11:34.000Z',
   'text': 'Just dropped NEW @skims Outdoor! Shop now at https://t.co/Qsy51S3rtD https://t.co/Hxa9Nyg2gH',
   'context_annotations': [{'domain': {'id': '10',
      'name': 'Person',
      'description': 'Named people in the world like Nelson Mandela'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}},
    {'domain': {'id': '58',
      'name': 'Entertainment Personality',
      'description': 'An entertainment personality in the world, like Anderson Cooper or Miranda Sings'},
     'entity': {'id': '806570121959383040',
      'name': 'Kim Kardashian',
      'description': 'Kim Kardashian'}}]}],
 'meta': {'newest_id': '1484287511341899776',
  'oldest_id': '1484287511341899776',
  'result_count': 1}}

In [8]:
'''
Writing Tweets to a text file

This example shows how you can write the Tweet IDs for each Tweet obtained 
for a search result, to a text file.

Make sure to replace the file_name with the a name of your chosing.

If you wish to write other fields to the text file, make sure to adjust the script below accordingly.
'''

file_name = 'tweets.txt'

df1.to_csv(file_name, index=False, encoding='utf-8')

# If you want a different delimiter, say, tab or '\t'
# You can do:
#    df2.to_csv(file_name, index=False, encoding='utf-8', sep='\t')