snscrape

Ref: https://github.com/JustAnotherArchivist/snscrape

In [1]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

Scraping a specific Twitter user‚Äôs tweets

Let's use this handle: @KimKardashian

Using the code, we can scrape 100 tweets from Twitter user @KimKardashian.
We then pulled the DateTime, tweet id, text, and username attributes from the tweet objects.

In [2]:
# Creating list to append tweet data 
tweets_list1 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
handle = 'KimKardashian'

# declare a username 
for i, tweet in enumerate(sntwitter.TwitterSearchScraper('from:' + handle).get_items()): 
    if i > 10: #number of tweets you want to scrape
        break
        
    #declare the attributes to be returned
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
    
# Creating a dataframe from the tweets list above 
tweets_df1 = pd.DataFrame(tweets_list1, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

In [3]:
tweets_df1

,Datetime,Tweet Id,Text,Username
0,2022-01-26 02:55:09+00:00,1486170817310298115,Which are you guys excited for tomorrow??? I l...,KimKardashian
1,2022-01-25 23:52:13+00:00,1486124781430718465,long time no sea üåä üêö https://t.co/LtJrwUQ8x7,KimKardashian
2,2022-01-25 17:01:34+00:00,1486021437446000641,Just drop NEW @skims for @TeamUSA! Shop now fo...,KimKardashian
3,2022-01-24 19:39:45+00:00,1485698860496285700,"My condolences go to Manfred‚Äôs family, friends...",KimKardashian
4,2022-01-24 19:39:41+00:00,1485698841265336323,You always said beauty will save the world - a...,KimKardashian
5,2022-01-24 19:39:34+00:00,1485698812630863873,There was so much more for you to show the wor...,KimKardashian
6,2022-01-24 19:39:29+00:00,1485698790677835776,Manfred Thierry Mugler üíî My heart breaks. Ther...,KimKardashian
7,2022-01-21 18:29:10+00:00,1484593931157336065,Just added new items to my #KardashianKloset h...,KimKardashian
8,2022-01-21 16:50:04+00:00,1484568994463895552,Always ‚úåüèºüíó https://t.co/w3KBqX7RbW,KimKardashian
9,2022-01-20 22:11:34+00:00,1484287511341899776,Just dropped NEW @skims Outdoor! Shop now at h...,KimKardashian
10,2022-01-19 20:02:02+00:00,1483892525014282243,You can expect a wide range of scent notes fro...,KimKardashian

Scraping tweets from a text search query

Using the code below, we are scraping 100 tweets between June 14, 2020, and August 31, 2021,
with the keywords 'SSR Bollywood'.

I then pulled attributes DateTime, tweet id, text, and username from the tweet objects.

In [4]:
# Creating list to append tweet data to
tweets_list2 = []

# search terms
search_terms = 'SSR Bollywood'

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_terms + ' since:2021-06-14 until:2021-08-31').get_items()):
    if i > 100:
        break
    #declare the attributes to be returned
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

In [5]:
tweets_df2

,Datetime,Tweet Id,Text,Username
0,2021-08-30 22:49:08+00:00,1432475503227777024,@AnupamPKher @mairal Sir you will always be a ...,sparikh20241
1,2021-08-30 20:41:25+00:00,1432443362066448388,"@djfreezechill So much Police, politicians SSR...",NYTraveler2
2,2021-08-30 19:21:13+00:00,1432423179532836868,PAYBACK IS ALWAYS HARD.\nBOLLYWOOD MADE SSR'S...,sheelawood
3,2021-08-30 19:09:56+00:00,1432420339368148992,Boyc0tt Bollywood forever and justice for inno...,AdnanMa47574375
4,2021-08-30 18:29:15+00:00,1432410099104948224,Methi Boliyan Status #Bollywood #SSR https://t...,kl_angkon
...,...,...,...,...
96,2021-08-29 13:22:24+00:00,1431970491514851328,@Aaaaaaastha @Sushantify I support Kizie @Sush...,___avikaaaaa
97,2021-08-29 13:16:43+00:00,1431969062460944391,"SSR Was Not In DANGER,\nSSR Himself Is The DAN...",ToushnikY
98,2021-08-29 12:45:28+00:00,1431961196828131329,‡§§‡•Å‡§Æ ‡§Ö‡§ó‡§∞ ‡§Æ‡•Å‡§ù‡§ï‡•ã ‡§® follow karo \n‡§§‡•ã ‡§ï‡•ã‡§à ‡§¨‡§æ‡§§ ‡§®‡§π‡•Ä‡§Ç\...,Deepa_Sinha06
99,2021-08-29 12:41:28+00:00,1431960188035088385,People of this Democratic Nation Unanimously r...,SSRjustice2020
100,2021-08-29 12:21:54+00:00,1431955264261935113,@QaafiranaaSaHai Kriti is ssr's best friend th...,Carol_4_SSR