tweepy

Official documentation: https://docs.tweepy.org/en/stable/

Ref: https://dev.to/twitterdev/a-comprehensive-guide-for-using-the-twitter-api-v2-using-tweepy-in-python-15d9

In [22]:
import tweepy
import datetime
import pandas as pd
import json
import requests

In [23]:
# Paste in your own bearer token
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAOlFYQEAAAAA564Nq2buxWcuVMiwrxqNcrlFwfI%3DO6AkqhR3vBDKQnVJWaL04FQp0yaMBbz7GCeCLWwdUhba1NU6le'

client = tweepy.Client(bearer_token=BEARER_TOKEN, return_type=requests.Response)

In [43]:
'''
Searching for Tweets from the last 7 days

We can use the search_recent_tweets function available in Tweepy.
You will have to pass it a search query to specify the data that you are looking for.

Below, we will search for for Tweets from the last days from the 
Twitter handle realDonaldTrump and we are excluding retweets using -is:retweet.

By default, a request returns 10 Tweets.
If you want more than 10 Tweets per request, you can specify that using the max_results parameter.
The maximum Tweets per request is 100.
'''
# Replace with your own search query
# handle = 'KimKardashian'
handle = 'elonmusk'
query = 'from:' + handle + ' -is:retweet'

tweets1 = client.search_recent_tweets(
            query=query,
            tweet_fields=['context_annotations', 'created_at'],
            max_results=10)

In [44]:
'''
Convert to pandas Dataframe
'''

# Save data as dictionary
tweets_dict1 = tweets1.json()
# tweets_dict1
# Extract "data" value from dictionary
tweets_data1 = tweets_dict1['data'] 

# Transform to pandas Dataframe
df1 = pd.json_normalize(tweets_data1)

df1

,context_annotations,created_at,text,id
0,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-10T05:04:48.000Z,https://t.co/EmLdMdPizM,1491639263686844418
1,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-10T04:53:52.000Z,https://t.co/BDP2yRxYpI,1491636510642167809
2,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-10T04:46:57.000Z,https://t.co/j1j32Iu1oA,1491634769934753799
3,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-10T04:31:58.000Z,Tower arms are lifting Starship onto Super Hea...,1491631000232759305
4,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-09T21:56:08.000Z,@slashdot This would generate a lot of goodwill,1491531384900435972
5,"[{'domain': {'id': '46', 'name': 'Brand Catego...",2022-02-09T21:49:54.000Z,@TechCrunch ðŸ§² â›ˆ ðŸª¦,1491529818986487816
6,"[{'domain': {'id': '46', 'name': 'Brand Catego...",2022-02-09T21:34:58.000Z,@archillect ðŸ–¤,1491526060009213955
7,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-09T21:34:13.000Z,Much appreciated! https://t.co/ncGA3LA7x9,1491525871517286404
8,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-09T21:22:15.000Z,@SawyerMerritt @WholeMarsBlog Model X is an ex...,1491522859616903168
9,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-09T20:16:48.000Z,@TheBabylonBee ðŸ¤£,1491506387297480709

In [45]:
'''
If you want to get Tweets for a specific time-period, you can specify the time-period
using the start_time and end_time parameters, as shown in the example below:
'''

# Replace with time period of your choice
start_time = '2022-02-04T00:00:00Z'

# Replace with time period of your choice
end_time = '2022-02-05T00:00:00Z'


# Replace with your own search query
handle = 'elonmusk'
query = 'from:' + handle + ' -is:retweet'

tweets2 = client.search_recent_tweets(
            query=query,
            tweet_fields=['context_annotations', 'created_at'],
            start_time=start_time,
            end_time=end_time,
            max_results=100)

'''
Convert to pandas Dataframe
'''
df2 = pd.json_normalize(tweets2)

tweets2.json()

{'data': [{'id': '1489672786683609091',
   'created_at': '2022-02-04T18:50:43.000Z',
   'text': '@Tesmanian_com A bigger win than it may seem',
   'context_annotations': [{'domain': {'id': '10',
      'name': 'Person',
      'description': 'Named people in the world like Nelson Mandela'},
     'entity': {'id': '808713037230157824',
      'name': 'Elon Musk',
      'description': 'Elon Musk'}},
    {'domain': {'id': '65',
      'name': 'Interests and Hobbies Vertical',
      'description': 'Top level interests and hobbies groupings, like Food or Travel'},
     'entity': {'id': '781974596148793345', 'name': 'Business & finance'}},
    {'domain': {'id': '66',
      'name': 'Interests and Hobbies Category',
      'description': 'A grouping of interests and hobbies entities, like Novelty Food or Destinations'},
     'entity': {'id': '857878777191211008',
      'name': 'Leadership',
      'description': 'Leadership'}},
    {'domain': {'id': '30',
      'name': 'Entities [Entity Service]',
      'description': 'Entity Service top level domain, every item that is in Entity Service should be in this domain'},
     'entity': {'id': '857879456773357569',
      'name': 'Technology',
      'description': 'Technology'}}]},
  {'id': '1489615144116174850',
   'created_at': '2022-02-04T15:01:40.000Z',
   'text': '@co_tesla ðŸ’¯',
   'context_annotations': [{'domain': {'id': '10',
      'name': 'Person',
      'description': 'Named people in the world like Nelson Mandela'},
     'entity': {'id': '808713037230157824',
      'name': 'Elon Musk',
      'description': 'Elon Musk'}},
    {'domain': {'id': '65',
      'name': 'Interests and Hobbies Vertical',
      'description': 'Top level interests and hobbies groupings, like Food or Travel'},
     'entity': {'id': '781974596148793345', 'name': 'Business & finance'}},
    {'domain': {'id': '66',
      'name': 'Interests and Hobbies Category',
      'description': 'A grouping of interests and hobbies entities, like Novelty Food or Destinations'},
     'entity': {'id': '857878777191211008',
      'name': 'Leadership',
      'description': 'Leadership'}},
    {'domain': {'id': '30',
      'name': 'Entities [Entity Service]',
      'description': 'Entity Service top level domain, every item that is in Entity Service should be in this domain'},
     'entity': {'id': '857879456773357569',
      'name': 'Technology',
      'description': 'Technology'}}]},
  {'id': '1489466267010543621',
   'created_at': '2022-02-04T05:10:05.000Z',
   'text': '@WholeMarsBlog ðŸ˜¢',
   'context_annotations': [{'domain': {'id': '10',
      'name': 'Person',
      'description': 'Named people in the world like Nelson Mandela'},
     'entity': {'id': '808713037230157824',
      'name': 'Elon Musk',
      'description': 'Elon Musk'}},
    {'domain': {'id': '65',
      'name': 'Interests and Hobbies Vertical',
      'description': 'Top level interests and hobbies groupings, like Food or Travel'},
     'entity': {'id': '781974596148793345', 'name': 'Business & finance'}},
    {'domain': {'id': '66',
      'name': 'Interests and Hobbies Category',
      'description': 'A grouping of interests and hobbies entities, like Novelty Food or Destinations'},
     'entity': {'id': '857878777191211008',
      'name': 'Leadership',
      'description': 'Leadership'}},
    {'domain': {'id': '30',
      'name': 'Entities [Entity Service]',
      'description': 'Entity Service top level domain, every item that is in Entity Service should be in this domain'},
     'entity': {'id': '857879456773357569',
      'name': 'Technology',
      'description': 'Technology'}}]}],
 'meta': {'newest_id': '1489672786683609091',
  'oldest_id': '1489466267010543621',
  'result_count': 3}}

In [46]:
df1

,context_annotations,created_at,text,id
0,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-10T05:04:48.000Z,https://t.co/EmLdMdPizM,1491639263686844418
1,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-10T04:53:52.000Z,https://t.co/BDP2yRxYpI,1491636510642167809
2,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-10T04:46:57.000Z,https://t.co/j1j32Iu1oA,1491634769934753799
3,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-10T04:31:58.000Z,Tower arms are lifting Starship onto Super Hea...,1491631000232759305
4,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-09T21:56:08.000Z,@slashdot This would generate a lot of goodwill,1491531384900435972
5,"[{'domain': {'id': '46', 'name': 'Brand Catego...",2022-02-09T21:49:54.000Z,@TechCrunch ðŸ§² â›ˆ ðŸª¦,1491529818986487816
6,"[{'domain': {'id': '46', 'name': 'Brand Catego...",2022-02-09T21:34:58.000Z,@archillect ðŸ–¤,1491526060009213955
7,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-09T21:34:13.000Z,Much appreciated! https://t.co/ncGA3LA7x9,1491525871517286404
8,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-09T21:22:15.000Z,@SawyerMerritt @WholeMarsBlog Model X is an ex...,1491522859616903168
9,"[{'domain': {'id': '10', 'name': 'Person', 'de...",2022-02-09T20:16:48.000Z,@TheBabylonBee ðŸ¤£,1491506387297480709

In [35]:
'''
Writing Tweets to a text file

This example shows how you can write the Tweet IDs for each Tweet obtained 
for a search result, to a text file.

Make sure to replace the file_name with the a name of your chosing.

If you wish to write other fields to the text file, make sure to adjust the script below accordingly.
'''

file_name = 'tweets.txt'

# df2.to_csv(file_name, index=False, encoding='utf-8')

# If you want a different delimiter, say, tab or '\t'
# You can do:
df2.to_csv(file_name, index=False, encoding='utf-8', sep='\t')